# Generated by Django 3.2.25 on 2025-09-04 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invoice.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('tax_id', models.CharField(max_length=50, unique=True, verbose_name='税号')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='开户行')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='银行账号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='发票号码')),
                ('invoice_code', models.CharField(max_length=50, verbose_name='发票代码')),
                ('invoice_date', models.DateField(verbose_name='开票日期')),
                ('invoice_type', models.CharField(choices=[('VAT_SPECIAL', '增值税专用发票'), ('VAT_GENERAL', '增值税普通发票'), ('ELECTRONIC', '电子发票'), ('PAPER', '纸质发票'), ('OTHER', '其他')], max_length=20, verbose_name='发票类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='税额')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价税合计')),
                ('seller_name', models.CharField(max_length=100, verbose_name='销售方名称')),
                ('seller_tax_id', models.CharField(max_length=50, verbose_name='销售方税号')),
                ('buyer_name', models.CharField(max_length=100, verbose_name='购买方名称')),
                ('buyer_tax_id', models.CharField(max_length=50, verbose_name='购买方税号')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('VERIFIED', '已验证'), ('REJECTED', '已拒绝'), ('USED', '已使用')], default='PENDING', max_length=20, verbose_name='状态')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已验证')),
                ('verification_date', models.DateTimeField(blank=True, null=True, verbose_name='验证时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file', models.FileField(blank=True, null=True, upload_to=invoice.models.Invoice.invoice_file_path, verbose_name='发票文件')),
                ('image', models.ImageField(blank=True, null=True, upload_to=invoice.models.Invoice.invoice_file_path, verbose_name='发票图片')),
            ],
            options={
                'verbose_name': '发票',
                'verbose_name_plural': '发票',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='月度限额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '发票类别',
                'verbose_name_plural': '发票类别',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总金额')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('SUBMITTED', '已提交'), ('APPROVED', '已批准'), ('REJECTED', '已拒绝'), ('PAID', '已支付')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reimbursements', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.company', verbose_name='所属公司')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reimbursements', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('invoices', models.ManyToManyField(related_name='reimbursements', to='invoice.Invoice', verbose_name='关联发票')),
            ],
            options={
                'verbose_name': '报销单',
                'verbose_name_plural': '报销单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='recognition/%Y%m%d/', verbose_name='文件')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='PENDING', max_length=20, verbose_name='状态')),
                ('result', models.TextField(blank=True, null=True, verbose_name='识别结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognitions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognitions', to='invoice.invoice', verbose_name='关联发票')),
            ],
            options={
                'verbose_name': '发票识别记录',
                'verbose_name_plural': '发票识别记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoicecategory', verbose_name='发票类别'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.company', verbose_name='所属公司'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
