# Generated by Django 4.2.24 on 2025-09-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_code',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_content',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='发票内容'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='项目名称'),
        ),
    ]
