# Generated by Django 4.2.24 on 2025-09-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_invoice_invoice_code_invoice_invoice_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='item_name',
        ),
    ]
