# Generated by Django 4.2.24 on 2025-09-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_invoice_item_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reimbursement',
        ),
    ]
