# Generated by Django 4.2.24 on 2025-09-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_delete_reimbursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerecognition',
            name='status',
            field=models.CharField(choices=[('PENDING', '待处理'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('FAILED', '失败'), ('MANUAL_COMPLETED', '手动完成')], default='PENDING', max_length=20, verbose_name='状态'),
        ),
    ]
