# Generated by Django 4.2.24 on 2025-09-05 03:07

from django.db import migrations, models
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoicerecognition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerecognition',
            name='file',
            field=models.FileField(upload_to=invoice.models.invoice_recognition_file_path, verbose_name='文件'),
        ),
    ]
